### ISSUE TITLE
plugin.video.xxx-o-dus Version 4..00.037 Fail to start on Kodi 18.6 Windows 10 64

### ISSUE THREAD

**Issue by TheZvek** [nemesis668/repository.streamarmy#6]
tried re-install from http, Local file, remove all folders and nothing works...
use to work before updating.

error details:

2020-05-16 08:14:57.010 T:1132   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name URL_Dispatcher
                                            Traceback (most recent call last):
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\default.py", line 11, in <module>
                                                eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
                                              File "<string>", line 15, in <module>
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\resources\lib\modules\utils.py", line 10, in <module>
                                                from url_dispatcher import URL_Dispatcher
                                            ImportError: cannot import name URL_Dispatcher
                                            -->End of Python script error report<--
2020-05-16 08:14:57.030 T:1564   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.xxx-o-dus/
2020-05-16 08:14:57.042 T:9676   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xxx-o-dus/) failed
**

**Comment by TheZvek** [comment]
anyone ?
something ?
